# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Citeproc < Formula
  desc ""
  homepage ""
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/front-matter/invenio/releases/download/v0.1.1/invenio_Darwin_x86_64.tar.gz"
      sha256 "2ebabc614afd286cdda9d613430930e8093c4ce834e7f3641405ce9b930b8f62"

      def install
        bin.install "invenio"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/front-matter/invenio/releases/download/v0.1.1/invenio_Darwin_arm64.tar.gz"
      sha256 "a3a5fa8553085cc8e32d8b7e04ec2c847b80e3cedd15ace9cb90eaeb1ffb30d0"

      def install
        bin.install "invenio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/front-matter/invenio/releases/download/v0.1.1/invenio_Linux_x86_64.tar.gz"
        sha256 "dd871dae864d9b2cb518890d0c5199ea8ddc67162fd166141ed7871ca5718540"

        def install
          bin.install "invenio"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/front-matter/invenio/releases/download/v0.1.1/invenio_Linux_arm64.tar.gz"
        sha256 "674aff884fa4cf97143aa564e19cb360bb2ad01f42f24a2689e50ed35afe0b10"

        def install
          bin.install "invenio"
        end
      end
    end
  end
end
