# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Invenio < Formula
  desc ""
  homepage ""
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/front-matter/invenio/releases/download/v0.1.3/invenio_Darwin_x86_64.tar.gz"
      sha256 "7035ad286966fd7ba36e2f3277a8fae9c6220dc8731fefe532f726f37e013936"

      def install
        bin.install "invenio"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/front-matter/invenio/releases/download/v0.1.3/invenio_Darwin_arm64.tar.gz"
      sha256 "31e77a15b153ea1d19a16c7bcdcc18669a66b1714c004e1e2406529d093bd8c8"

      def install
        bin.install "invenio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/front-matter/invenio/releases/download/v0.1.3/invenio_Linux_x86_64.tar.gz"
        sha256 "d5c22f902c0901622d073d9cd2682ff22811ba1766d0344ecae6c3017f9cd061"

        def install
          bin.install "invenio"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/front-matter/invenio/releases/download/v0.1.3/invenio_Linux_arm64.tar.gz"
        sha256 "e452bc64551ee864f5c5f6a6546189ce1c1a35cbfac1394a8784f06cafbedb1b"

        def install
          bin.install "invenio"
        end
      end
    end
  end
end
