# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Inveniordm < Formula
  desc ""
  homepage ""
  version "0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/front-matter/inveniordm/releases/download/v0.4/inveniordm_Darwin_x86_64.tar.gz"
      sha256 "8bce9755cffd10e5d490f9273d2faa62eb333c7696080b283f835955a55252e4"

      def install
        bin.install "inveniordm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/front-matter/inveniordm/releases/download/v0.4/inveniordm_Darwin_arm64.tar.gz"
      sha256 "1c5c2b423273858219f72a4c52b25be456a915fb555b59d287a592c4e2ef0750"

      def install
        bin.install "inveniordm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/front-matter/inveniordm/releases/download/v0.4/inveniordm_Linux_x86_64.tar.gz"
      sha256 "42f1ade5cf5292d2a5b0efb9016dd859349b0658c5a5a9b087a1f9389a49c2b0"
      def install
        bin.install "inveniordm"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/front-matter/inveniordm/releases/download/v0.4/inveniordm_Linux_arm64.tar.gz"
      sha256 "99ddf56430eff9bf8a9b8272143fb000363443063957ed316efaf606d18ee284"
      def install
        bin.install "inveniordm"
      end
    end
  end
end
