# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Inveniordm < Formula
  desc ""
  homepage ""
  version "0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/front-matter/inveniordm/releases/download/v0.3/inveniordm_Darwin_x86_64.tar.gz"
      sha256 "84dc8b6c77ab0c6e73c9f24225b88c27ed0ba3e88382fe3dbc6e761206d2a181"

      def install
        bin.install "inveniordm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/front-matter/inveniordm/releases/download/v0.3/inveniordm_Darwin_arm64.tar.gz"
      sha256 "1c067fc2da901fd13814c61c2c2ea31310251a0fa1dd9623432e137cfe823f54"

      def install
        bin.install "inveniordm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/front-matter/inveniordm/releases/download/v0.3/inveniordm_Linux_x86_64.tar.gz"
      sha256 "14ec580015775ac2117a70355594f74cdfbe606a3c2d6d81f8f9a00e2ef985fa"
      def install
        bin.install "inveniordm"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/front-matter/inveniordm/releases/download/v0.3/inveniordm_Linux_arm64.tar.gz"
      sha256 "85eaee1944540d2c6de44fd272b6c7f6e66ff8c1277436e9defa16e18b4a0d94"
      def install
        bin.install "inveniordm"
      end
    end
  end
end
