# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Invenio < Formula
  desc ""
  homepage ""
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/front-matter/invenio/releases/download/v0.1.2/invenio_Darwin_x86_64.tar.gz"
      sha256 "e94cafe8f60fe533573fe480c7e458d7f7186afb5592eb9a7eea3effc2b4254a"

      def install
        bin.install "invenio"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/front-matter/invenio/releases/download/v0.1.2/invenio_Darwin_arm64.tar.gz"
      sha256 "94332d8c76217c1903e278f2f78bb42dba06aed9733210f4c90f9e91bc7cf998"

      def install
        bin.install "invenio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/front-matter/invenio/releases/download/v0.1.2/invenio_Linux_x86_64.tar.gz"
        sha256 "f2b1ac139f3da9a6276e2afcf8e86f885a0d805945793c534c86b883453b553f"

        def install
          bin.install "invenio"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/front-matter/invenio/releases/download/v0.1.2/invenio_Linux_arm64.tar.gz"
        sha256 "3918696427d0886bf61ec0651798c8d9f3306092b5597ddca76faf43d10c2f47"

        def install
          bin.install "invenio"
        end
      end
    end
  end
end
