# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Inveniordm < Formula
  desc ""
  homepage ""
  version "0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/front-matter/inveniordm/releases/download/v0.5/inveniordm_Darwin_x86_64.tar.gz"
      sha256 "1dea5d52d9b0c61dbfa2ae4a20e92dae46f59cf4cccf3309b6c25bb803314f43"

      def install
        bin.install "inveniordm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/front-matter/inveniordm/releases/download/v0.5/inveniordm_Darwin_arm64.tar.gz"
      sha256 "018cbfbdb4fe9e961d11ac29459a4f6e68bdc6be657e1d8fed1cd7267d35cd28"

      def install
        bin.install "inveniordm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/front-matter/inveniordm/releases/download/v0.5/inveniordm_Linux_x86_64.tar.gz"
      sha256 "f33d10418ddb9b26baf354fdeea80fa4db2b38aed1795a05a737d02f00320afd"
      def install
        bin.install "inveniordm"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/front-matter/inveniordm/releases/download/v0.5/inveniordm_Linux_arm64.tar.gz"
      sha256 "29769232938fc8029731bc9258a1315a88e748b6439333f4b1d4f65cc0d6567e"
      def install
        bin.install "inveniordm"
      end
    end
  end
end
